#! /bin/sh
#
# Created by NJG on Thu May  9 11:43:50  2002
#
#  $Id: Getversion,v 4.3 2008/05/28 03:13:54 pfeller Exp $
#

cat lib/PDQ_Lib.h | awk '
/version/ && /PDQ/ && /Analyzer/ { print $5 " " $7 " " $8} '

ls -l lib | awk '
/libpdq/ { print "Last compiled on " $6 " " $7 " " $8} '

exit 0
