#
#  $Id: Makefile.cygwin,v 4.5 2009/04/03 02:19:41 pfeller Exp $
#
#-----------------------------------------------------------

CFLAGS = -ggdb

OBJ     = \
	MVA_Approx.o \
	MVA_Canon.o \
	MVA_Solve.o \
	PDQ_Build.o \
	PDQ_Exact.o \
	PDQ_Globals.o \
	PDQ_MServer.o \
	PDQ_Report.o \
	PDQ_Utils.o

#-----------------------------------------------------------

all:	$(OBJ)
	-ar -rv libpdq.a $(OBJ)
	-ranlib libpdq.a          # Cygwin

#-----------------------------------------------------------

clean:
	-/bin/rm *.o libpdq.a *~

#-----------------------------------------------------------

