#
#  $Id: Makefile.gcc,v 4.5 2009/04/08 02:18:04 pfeller Exp $
#
#-----------------------------------------------------------

OBJ   = \
	MVA_Approx.o \
	MVA_Canon.o \
	MVA_Solve.o \
	PDQ_Build.o \
	PDQ_Exact.o \
	PDQ_Globals.o \
	PDQ_MServer.o \
	PDQ_Report.o \
	PDQ_Utils.o

#-----------------------------------------------------------

all:	$(OBJ)
	-ar rv libpdq.a *.o

#-----------------------------------------------------------

clean:
	-/bin/rm *.o

#-----------------------------------------------------------

