#
#  $Id: Makefile,v 4.3 2009/04/03 02:19:41 pfeller Exp $
#
#---------------------------------------------------------------------

all:	test

#---------------------------------------------------------------------

test:
	./abcache.pl
	./cluster.pl
	./cs_baseline.pl
	./ebiz.pl
	./elephant.pl
	./feedback.pl
	./feedforward.pl
	./fesc.pl
	./florida.pl
	./httpd.pl
	./mm1.pl
	./mm1n.pl
	./multibus.pl
	./mwl.pl
	./passport.pl
	./shadowcpu.pl

#---------------------------------------------------------------------

clean:
	-rm *.res

#---------------------------------------------------------------------

